CREATE TABLE `characters` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`user_id` INT(11) NOT NULL DEFAULT '0',
	`name` VARCHAR(13) NOT NULL COLLATE 'utf8mb4_unicode_ci',
	`position` INT(11) NOT NULL DEFAULT '0',
	`type` INT(11) NOT NULL DEFAULT '1',
	`experience` INT(11) NOT NULL DEFAULT '0',
	`level` INT(11) NOT NULL DEFAULT '1',
	`rank_exp` INT(11) NOT NULL DEFAULT '0',
	`rank` INT(11) NOT NULL DEFAULT '0',
	`health` INT(11) NOT NULL DEFAULT '5500',
	`luck` INT(11) NOT NULL DEFAULT '0',
	`speed` INT(11) NOT NULL DEFAULT '1000',
	`att_min` INT(11) NOT NULL DEFAULT '350',
	`att_max` INT(11) NOT NULL DEFAULT '490',
	`att_trans_min` INT(11) NOT NULL DEFAULT '700',
	`att_trans_max` INT(11) NOT NULL DEFAULT '980',
	`att_critical` INT(11) NOT NULL DEFAULT '0',
	`att_evade` INT(11) NOT NULL DEFAULT '0',
	`att_ranged` INT(11) NOT NULL DEFAULT '1000',
	`trans_special` INT(11) NOT NULL DEFAULT '0',
	`trans_guage` INT(11) NOT NULL DEFAULT '1000',
	`trans_def` INT(11) NOT NULL DEFAULT '0',
	`trans_att` INT(11) NOT NULL DEFAULT '1000',
	`trans_speed` INT(11) NOT NULL DEFAULT '0',
	`currency_botstract` INT(11) NOT NULL DEFAULT '0',
	`currency_gigas` INT(11) NOT NULL DEFAULT '3000',
	PRIMARY KEY (`id`) USING BTREE,
	UNIQUE INDEX `name` (`name`) USING BTREE
)
COLLATE='utf8mb4_unicode_ci'
ENGINE=InnoDB;
